//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaySettCompany.WebApp.PurchaseService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PurchaseService.IPurchase")]
    public interface IPurchase {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchase/GetAllProducts", ReplyAction="http://tempuri.org/IPurchase/GetAllProductsResponse")]
        PaySettCompany.Entities.ProductsList[] GetAllProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchase/GetAllProducts", ReplyAction="http://tempuri.org/IPurchase/GetAllProductsResponse")]
        System.Threading.Tasks.Task<PaySettCompany.Entities.ProductsList[]> GetAllProductsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchase/InsertProduct", ReplyAction="http://tempuri.org/IPurchase/InsertProductResponse")]
        void InsertProduct(PaySettCompany.Entities.Purchase purchase);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchase/InsertProduct", ReplyAction="http://tempuri.org/IPurchase/InsertProductResponse")]
        System.Threading.Tasks.Task InsertProductAsync(PaySettCompany.Entities.Purchase purchase);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPurchaseChannel : PaySettCompany.WebApp.PurchaseService.IPurchase, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PurchaseClient : System.ServiceModel.ClientBase<PaySettCompany.WebApp.PurchaseService.IPurchase>, PaySettCompany.WebApp.PurchaseService.IPurchase {
        
        public PurchaseClient() {
        }
        
        public PurchaseClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PurchaseClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PurchaseClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PurchaseClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PaySettCompany.Entities.ProductsList[] GetAllProducts() {
            return base.Channel.GetAllProducts();
        }
        
        public System.Threading.Tasks.Task<PaySettCompany.Entities.ProductsList[]> GetAllProductsAsync() {
            return base.Channel.GetAllProductsAsync();
        }
        
        public void InsertProduct(PaySettCompany.Entities.Purchase purchase) {
            base.Channel.InsertProduct(purchase);
        }
        
        public System.Threading.Tasks.Task InsertProductAsync(PaySettCompany.Entities.Purchase purchase) {
            return base.Channel.InsertProductAsync(purchase);
        }
    }
}
